services:
  # YouTube Bot Service
  youtube-bot:
    build: .
    container_name: youtube-bot
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - TELEGRAM_API_URL=${TELEGRAM_API_URL}
      - PATH_TO_LOAD_VIDEO=${PATH_TO_LOAD_VIDEO}
      - PATH_TO_LOAD_AUDIO=${PATH_TO_LOAD_AUDIO}
      - PATH_TO_LOAD_IMG=${PATH_TO_LOAD_IMG}
      - PROXY_URL=${PROXY_URL}

    volumes:
      - ${PATH_TO_LOAD_VIDEO}:/tmp/videos
      - ${PATH_TO_LOAD_AUDIO}:/tmp/audio
      - ${PATH_TO_LOAD_IMG}:/tmp/images

    networks:
      - monitoring
    depends_on:
      - mysql
      - telegram-api
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge
