services:
  # YouTube Bot Service
  youtube-bot:
    build: .
    container_name: youtube-bot
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - TELEGRAM_API_URL=${TELEGRAM_API_URL}
      - PATH_TO_LOAD_VIDEO=${PATH_TO_LOAD_VIDEO}
      - PATH_TO_LOAD_AUDIO=${PATH_TO_LOAD_AUDIO}
      - PATH_TO_LOAD_IMG=${PATH_TO_LOAD_IMG}
      - PROXY_URL=${PROXY_URL}

    volumes:
      - /samba/downloads/video:${PATH_TO_LOAD_VIDEO}
      - /samba/downloads/audio:${PATH_TO_LOAD_AUDIO}
      - /samba/downloads/images:${PATH_TO_LOAD_IMG}

    networks:
      - monitoring

    restart: unless-stopped

networks:
  monitoring:
    driver: bridge
